export const PLANS = {
  esencial: {
    id: "esencial",
    name: "Esencial",
    price: 9.99,
    description: "1-2 productos o 1 servicio básico",
    maxCategories: 2,
    maxProducts: 0, // No product selection for Esencial
    features: ["1-2 productos premium", "1 servicio básico", "Envío gratis", "Soporte por email"],
  },
  premium: {
    id: "premium",
    name: "Premium",
    price: 24.99,
    description: "2-3 productos + 1 servicio",
    maxCategories: 4,
    maxProducts: 3,
    features: [
      "2-3 productos premium",
      "1 servicio incluido",
      "Productos extra disponibles",
      "Cashback 3% en referidos",
      "Envío gratis",
      "Soporte prioritario",
    ],
  },
  deluxe: {
    id: "deluxe",
    name: "Deluxe",
    price: 39.99,
    description: "3+ productos + 2 servicios premium + beneficios exclusivos",
    maxCategories: "all",
    maxProducts: 6,
    features: [
      "3+ productos premium",
      "2 servicios premium",
      "Servicios extra disponibles",
      "Cashback 8% en referidos Deluxe",
      "Acceso a todas las categorías",
      "Beneficios exclusivos",
      "Envío gratis",
      "Soporte VIP 24/7",
    ],
  },
} as const

export const CATEGORIES = [
  {
    id: "facial",
    name: "Belleza facial",
    icon: "✨",
    available: true,
  },
  {
    id: "makeup",
    name: "Maquillaje",
    icon: "💄",
    available: true,
  },
  {
    id: "corporal",
    name: "Cuidado corporal",
    icon: "🌿",
    available: true,
  },
  {
    id: "cabello",
    name: "Cabello",
    icon: "💇",
    available: true,
  },
  {
    id: "bienestar",
    name: "Bienestar emocional",
    icon: "💆",
    available: true,
  },
  {
    id: "higiene",
    name: "Higiene femenina",
    icon: "🌸",
    available: true,
  },
  {
    id: "maternidad",
    name: "Maternidad",
    icon: "🤰",
    available: false,
  },
  {
    id: "lenceria",
    name: "Lencería",
    icon: "👙",
    available: false,
  },
  {
    id: "perfumeria",
    name: "Perfumería",
    icon: "🌺",
    available: false,
  },
] as const

export const PRODUCTS = {
  facial: [
    {
      id: "serum-vitamin-c",
      name: "Sérum Vitamina C",
      brand: "Florina CR",
      description: "Sérum antioxidante para luminosidad y protección",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "crema-hidratante",
      name: "Crema Hidratante Facial",
      brand: "Flormar",
      description: "Hidratación profunda para todo tipo de piel",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "mascarilla-arcilla",
      name: "Mascarilla de Arcilla",
      brand: "Natura",
      description: "Purifica y minimiza poros",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "contorno-ojos",
      name: "Contorno de Ojos",
      brand: "Avon",
      description: "Reduce ojeras y líneas de expresión",
      image: "/placeholder.svg?height=200&width=200",
      available: false,
    },
  ],
  makeup: [
    {
      id: "base-maquillaje",
      name: "Base de Maquillaje",
      brand: "Flormar",
      description: "Cobertura natural de larga duración",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "labial-mate",
      name: "Labial Mate",
      brand: "Florina CR",
      description: "Color intenso y acabado mate",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "paleta-sombras",
      name: "Paleta de Sombras",
      brand: "Natura",
      description: "12 tonos versátiles para cualquier look",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "rimel-volumen",
      name: "Rímel Volumen",
      brand: "Avon",
      description: "Pestañas voluminosas y definidas",
      image: "/placeholder.svg?height=200&width=200",
      available: false,
    },
  ],
  corporal: [
    {
      id: "crema-corporal",
      name: "Crema Corporal Nutritiva",
      brand: "Natura",
      description: "Hidratación intensa para piel suave",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "exfoliante-corporal",
      name: "Exfoliante Corporal",
      brand: "Florina CR",
      description: "Elimina células muertas y suaviza",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "aceite-corporal",
      name: "Aceite Corporal",
      brand: "Flormar",
      description: "Nutrición profunda con aroma relajante",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
  ],
  cabello: [
    {
      id: "shampoo-reparador",
      name: "Shampoo Reparador",
      brand: "Natura",
      description: "Repara y fortalece cabello dañado",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "mascarilla-capilar",
      name: "Mascarilla Capilar",
      brand: "Avon",
      description: "Tratamiento intensivo para cabello sedoso",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "aceite-capilar",
      name: "Aceite Capilar",
      brand: "Florina CR",
      description: "Nutrición y brillo natural",
      image: "/placeholder.svg?height=200&width=200",
      available: false,
    },
  ],
  bienestar: [
    {
      id: "vela-aromatica",
      name: "Vela Aromática",
      brand: "Natura",
      description: "Relajación y aromaterapia",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "sales-baño",
      name: "Sales de Baño",
      brand: "Flormar",
      description: "Baño relajante y desestresante",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
  ],
  higiene: [
    {
      id: "gel-intimo",
      name: "Gel Íntimo",
      brand: "Florina CR",
      description: "Cuidado delicado y protección",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
    {
      id: "toallitas-intimas",
      name: "Toallitas Íntimas",
      brand: "Natura",
      description: "Frescura y limpieza en cualquier momento",
      image: "/placeholder.svg?height=200&width=200",
      available: true,
    },
  ],
} as const

export const INTERESTS = [
  { id: "productos", name: "Productos", icon: "🧴" },
  { id: "servicios", name: "Servicios", icon: "✂️" },
  { id: "ambos", name: "Ambos", icon: "🌟" },
] as const

export const SOCIAL_LINKS = {
  email: "hello@luvelle.club",
  whatsapp: "https://wa.me/15557792120",
  instagram: "https://www.instagram.com/luvelle_club",
  tiktok: "https://www.tiktok.com/@luvelle.club",
  linkedin: "https://www.linkedin.com/company/luvelleai",
  twitter: "https://twitter.com/LuVelleAi",
} as const
